apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vocal-remover.fullname" . }}-secrets
  labels:
    {{- include "vocal-remover.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ACCESS_KEY: {{ .Values.minio.auth.accessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.auth.secretKey | quote }}
